### ISSUE TITLE
Web page not available

### ISSUE THREAD

**Issue by ElHadjiAlyKane** [develtar/qt-pdf-viewer-library#7] opened 2023-12-01 20:06 UTC
I compiled the example available with your project. The application compiles and runs on the Android device. The problem is that the web view reports that the web page cannot be loaded: file:///data/user/0/it.ltdev.qt.pdfviewer/files/libs/pdfjs/viewer.html.
At the web page of Qt Creator, the application reports : I chromium: [INFO:CONSOLE(1)] "Uncaught ReferenceError: loadDocument is not defined", source: chrome-error://chromewebdata/ (1)

**Comment by develtar** [comment] 2023-12-07 19:22
Hi @ElHadjiAlyKane, the problem is the same of issue #6 

It is related to the latest changes in the android SDK: since API level 30 the native Android WebView has the file access disabled by default.

**Comment by develtar** [comment] 2023-12-07 19:22
Duplicate of #6

**Closed as completed** 2023-12-07 19:23 UTC
